# Generated by Django 4.2.20 on 2025-04-30 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('first_review', 'First_Review'), ('publish', 'Publish'), ('donor_find', 'Donor_Find'), ('second_review', 'Second_Review'), ('transportation', 'Transportation'), ('complated', 'Complated'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], max_length=20)),
                ('note', models.TextField()),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='made_donations', to=settings.AUTH_USER_MODEL)),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='need.kind')),
                ('needy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_donations', to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('publish', django.db.models.manager.Manager()),
            ],
        ),
    ]
