# Generated by Django 4.2.20 on 2025-04-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('need', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='need',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='need',
            name='status',
            field=models.CharField(choices=[('first_review', 'First_Review'), ('publish', 'Publish'), ('donor_find', 'Donor_Find'), ('second_review', 'Second_Review'), ('transportation', 'Transportation'), ('complated', 'Complated'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='first_review', max_length=20),
        ),
    ]
