# Generated by Django 4.2.20 on 2025-04-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('need', '0002_alter_need_note_alter_need_status'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='need',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='need',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='need',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
