# Generated by Django 4.2.20 on 2025-04-30 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('need', '0004_alter_need_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='need',
            name='address',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
