# Generated by Django 4.2.20 on 2025-05-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('need', '0005_need_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='need',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
