# Generated by Django 4.2.20 on 2025-05-01 19:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('need', '0006_alter_need_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='need',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
