# Generated by Django 4.2.20 on 2025-05-01 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('need', '0007_need_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='need',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='need',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='made_donations', to=settings.AUTH_USER_MODEL),
        ),
    ]
