# Generated by Django 4.2.20 on 2025-05-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('need', '0008_alter_need_address_alter_need_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='need',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='need',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
