# Generated by Django 5.2 on 2025-05-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('need', '0009_need_slug_alter_need_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='kind',
            name='slug',
            field=models.SlugField(default='asd', max_length=40),
            preserve_default=False,
        ),
    ]
