# Generated by Django 4.2.21 on 2025-05-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('need', '0010_kind_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kind',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='kind',
            name='slug',
            field=models.SlugField(max_length=40, unique=True),
        ),
    ]
