# Generated by Django 4.2.11 on 2025-05-23 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('need', '0011_alter_kind_name_alter_kind_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_first_name', models.CharField(max_length=50)),
                ('donor_last_name', models.CharField(max_length=50)),
                ('confirmed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_offers', to=settings.AUTH_USER_MODEL)),
                ('need', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='need.need')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
