# Generated by Django 4.2.11 on 2025-05-25 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('need', '0012_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='need',
            name='status',
            field=models.CharField(choices=[('publish', 'Publish'), ('donor_find', 'Donor_Find'), ('transportation', 'Transportation'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='publish', max_length=20),
        ),
    ]
