# Generated by Django 4.2.11 on 2025-05-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('need', '0012_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='need',
            name='status',
            field=models.CharField(choices=[('publish', 'Publish'), ('donor_find', 'Donor_Find'), ('transportation', 'Transportation'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='publish', max_length=20),
        ),
    ]
