# Generated by Django 4.2.11 on 2025-05-26 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('need', '0013_alter_need_status'),
        ('need', '0013_offer_courier_alter_need_status'),
    ]

    operations = [
    ]
