# Generated by Django 4.2.11 on 2025-05-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('need', '0014_merge_20250526_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='need',
            name='status',
            field=models.CharField(choices=[('publish', 'Publish'), ('donor_find', 'Donor_Find'), ('courier_request', 'Courier_Request'), ('courier_find', 'Courier_Find'), ('transportation', 'Transportation'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='publish', max_length=20),
        ),
    ]
