# Generated by Django 4.2.11 on 2025-05-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('need', '0015_offer_code_alter_need_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='need',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='need',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='need',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
