# Generated by Django 5.2 on 2025-05-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0002_alter_appuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='address',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='current_address',
            field=models.IntegerField(default=0),
        ),
    ]
