# Generated by Django 5.2.1 on 2025-05-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0003_appuser_address_appuser_current_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='slug',
            field=models.SlugField(default=1, max_length=40, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appuser',
            name='tel',
            field=models.IntegerField(unique=True),
        ),
    ]
