# Generated by Django 4.2.11 on 2025-05-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0004_role_slug_alter_appuser_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
