# Generated by Django 4.2.11 on 2025-05-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0006_alter_appuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='reset_token_expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
